### ISSUE TITLE
AttributeError: module 'docformatter' has no attribute '_main'

### ISSUE THREAD

**Issue by alfozan** [douglasfarinelli/pydecker#1]
Hello there,

When trying to run `pipenv run decker format` I get 

```
Traceback (most recent call last):
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/bin/decker", line 8, in <module>
    sys.exit(main())
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/decker/format/command.py", line 62, in format_command
    run_format(
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/decker/format/services.py", line 19, in run_format
    backend.run(config)
  File "/Users/USER/.local/share/virtualenvs/app-L-RL43Kr/lib/python3.10/site-packages/decker/format/backends/docformatter.py", line 20, in run
    docformatter._main(  # NOQA
AttributeError: module 'docformatter' has no attribute '_main'
```

Environment: 
```
python --version
Python 3.10.7
pipenv --version
pipenv, version 2023.2.18

OS: Mac 13.2.1
```

**Comment by douglasfarinelli** [comment]
Hi @alfozan! 

Thanks for the feedback!

I will launch a new release soon with some new features and corrections, mainly in terms of compatibility with other libs.

Thanks!

**Comment by ugleiton** [comment]
pip install docformatter==1.4
